name: mvsec_day1
val_batch_freq: 1500
data_loader:
  gpu: 0
  args:
    batch_size: 1
    pin_memory: false
    shuffle: false
    num_workers: 0
    prefetch_factor: 2


logger:
  saved_tensors:
    final_prediction:
    flow_gt_event_volume_new:

dataset:
  val:
    recurrent: false


postprocess:

metrics:
  final_prediction_nonseq: ["L1", "L2", "1PE", "3PE"]
    
hydra:
  output_subdir: null

defaults:
  - /validation/data_loader_val_base@_here_
  - /logger_base@_here_
  